### ISSUE TITLE
Unable to find scripts

### ISSUE THREAD

**Issue by ramsey** [yar3333/haxe-refactor#3]
When I run `haxelib run refactor`, the only two scripts I see listed are:

```
Scripts:
    dts_to_haxe
    php_to_haxe_lib
```

When I list the contents of the library directory, I appear to see all the scripts, though:

```
❯ ls /usr/local/lib/haxe/lib/refactor/4,2,0/scripts
as2_to_haxe.cmd  dts_to_haxe/     java_to_cs.cmd        php_to_haxe_extern.cmd
beauty_cpp.cmd   dts_to_haxe.cmd  js_to_haxe.cmd        php_to_haxe_lib/
beauty_haxe.cmd  haxe_to_cpp.cmd  php_to_haxe.json      php_to_haxe_typedef.cmd
beauty_html.cmd  haxe_to_cs.cmd   php_to_haxe.php       ts_to_haxe.cmd
cs_to_haxe.cmd   haxe_to_ts.cmd   php_to_haxe_code.cmd
```

Even though the scripts are there, `refactor` can't seem to find them:

```
❯ haxelib run refactor ts_to_haxe
ERROR: Unknow command 'ts_to_haxe'.
```

Is there some kind of `PATH` setting I'm missing that I need to set so that `refactor` can find its scripts?

**Comment by yar3333** [comment]
These *.cmd helpers for Windows only.

**Comment by ramsey** [comment]
I see. Thank you for the response!
